package com.wallee.terminallinker.feature.settings

import android.content.Context
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/** One resolved runtime dependency from the build-time license report (docs/05 Phase 6.3). */
data class OssComponent(val name: String, val version: String?, val license: String?, val url: String?)

/**
 * Reads `assets/oss_licenses.json`, generated by the `dependency-license-report` Gradle plugin from the
 * release runtime classpath. Missing or unreadable → empty list; the screen then shows only the curated entries.
 */
object OssLicenses {
    private val json = Json { ignoreUnknownKeys = true }

    fun load(context: Context): List<OssComponent> = runCatching {
        val text = context.assets.open(ASSET_NAME).bufferedReader().use { it.readText() }
        json.decodeFromString(Report.serializer(), text).dependencies
            .map { dependency ->
                val license = dependency.moduleLicenses.firstOrNull()
                OssComponent(
                    name = dependency.moduleName,
                    version = dependency.moduleVersion,
                    license = license?.moduleLicense,
                    url = license?.moduleLicenseUrl ?: dependency.moduleUrl,
                )
            }
            .sortedBy { it.name.lowercase() }
    }.getOrDefault(emptyList())

    @Serializable
    private data class Report(val dependencies: List<Dependency> = emptyList())

    @Serializable
    private data class Dependency(
        val moduleName: String,
        val moduleVersion: String? = null,
        val moduleUrl: String? = null,
        val moduleLicenses: List<License> = emptyList(),
    )

    @Serializable
    private data class License(
        @SerialName("moduleLicense") val moduleLicense: String? = null,
        @SerialName("moduleLicenseUrl") val moduleLicenseUrl: String? = null,
    )

    const val ASSET_NAME = "oss_licenses.json"
}
